const airlineFeatures: Record<string, { title: string; desc: string }[]> = {
    ALK: [
      { title: 'Transport-Related Expenses', desc: 'This captures all costs directly associated with moving passengers and cargo.' },
      { title: 'Passenger Services', desc: 'These are costs incurred for in-flight and ground services provided directly to passengers.' },
      { title: 'Income Before Taxes', desc: 'This is the airline’s profit or loss from all operations and non-operating items, before deducting income tax expense.' },
      { title: 'Property and Baggage', desc: 'This captures the airline’s income from checked- and carry-on baggage charges.' }
    ],
    AAL: [
      { title: 'Operating Margin', desc: 'Measures profitability relative to total revenue.' },
      { title: 'Passenger Revenue', desc: 'Core driver of American Airlines’ top-line growth.' },
      { title: 'CASM', desc: 'Cost per available seat mile – tracks cost efficiency.' },
      { title: 'Fuel Hedging Strategy', desc: 'Impacts risk management and long-term margin.' },
    ],
    DAL: [
      { title: 'Operating Revenue', desc: 'Total income generated by Delta from all operations.' },
      { title: 'Non-ticket Revenue', desc: 'Baggage fees, loyalty programs, and services.' },
      { title: 'Debt-to-Equity Ratio', desc: 'Helps assess financial stability and leverage.' },
      { title: 'Route Efficiency', desc: 'How effectively the airline optimizes flight paths and costs.' },
    ],
    // Add other airlines like UAL, JBLU, LUV, ULCC, ALGT as needed
  };
  
  export default airlineFeatures;
  