const airlineFeatures: Record<string, { title: string; desc: string }[]> = {
    ALK: [
      { title: 'Revenue per Seat', desc: 'Tracks how much income is generated per available seat.' },
      { title: 'Fuel Costs', desc: 'A major factor affecting airline expenses and margins.' },
      { title: 'Load Factor', desc: 'Percentage of seats filled on average across flights.' },
      { title: 'Debt Ratio', desc: 'Shows how leveraged the airline is with external financing.' },
    ],
    AAL: [
      { title: 'Operating Margin', desc: 'Measures profitability relative to total revenue.' },
      { title: 'Passenger Revenue', desc: 'Core driver of American Airlines’ top-line growth.' },
      { title: 'CASM', desc: 'Cost per available seat mile – tracks cost efficiency.' },
      { title: 'Fuel Hedging Strategy', desc: 'Impacts risk management and long-term margin.' },
    ],
    DAL: [
      { title: 'Operating Revenue', desc: 'Total income generated by Delta from all operations.' },
      { title: 'Non-ticket Revenue', desc: 'Baggage fees, loyalty programs, and services.' },
      { title: 'Debt-to-Equity Ratio', desc: 'Helps assess financial stability and leverage.' },
      { title: 'Route Efficiency', desc: 'How effectively the airline optimizes flight paths and costs.' },
    ],
    // Add other airlines like UAL, JBLU, LUV, ULCC, ALGT as needed
  };
  
  export default airlineFeatures;
  